const fs=require("fs"),assert=require("assert/strict");
const a=JSON.parse(fs.readFileSync("docs/launch/level1/prog-135-level1-public-surface-observation-human-action-completion-recovery-decision-human-decision-acknowledgment-retry-request.json","utf8"));
assert.equal(a.program_number,135);
assert.equal(a.retry_request.issued,true);
assert.equal(a.human_decision_acknowledgment.received,false);
assert.equal(a.human_decision_acknowledgment.validated,false);
assert.equal(a.human_decision_response.received,false);
assert.equal(a.human_decision_response.validated,false);
assert.equal(a.human_decision.recorded,false);
assert.equal(a.human_decision.validated,false);
assert.equal(a.human_decision.selected_recovery_decision_option,null);
assert.equal(a.recovery_execution.allowed,false);
assert.equal(a.recovery_execution.performed,false);
assert.equal(a.fail_closed.fail_closed_snapshot_active,true);
assert.equal(a.fail_closed.fail_closed_remains_active,true);
assert.equal(a.fail_closed.no_state_unlock,true);
assert.equal(a.readiness.external_customer_ready,false);
assert.equal(a.readiness.banking_pack_ready,false);
assert.equal(a.readiness.level1_launch_ready,false);
assert.equal(a.readiness.production_ready,false);
assert.equal(a.authority.ai_authority_allowed,false);
assert.equal(a.authority.legal_validity_claimed,false);
assert.equal(a.authority.accreditation_claimed,false);
assert.equal(a.authority.procurement_eligibility_claimed,false);
assert.equal(a.constraints.no_readiness_unlock,true);
assert.equal(a.next_required_program,"PROG-136-HBCE-LEVEL1-PUBLIC-SURFACE-OBSERVATION-HUMAN-ACTION-COMPLETION-RECOVERY-DECISION-HUMAN-DECISION-ACKNOWLEDGMENT-RETRY-ACKNOWLEDGMENT");
console.log("PROG_135_TEST=PASS");
