const fs=require("fs"),assert=require("assert/strict");
const a=JSON.parse(fs.readFileSync("docs/launch/level1/prog-167-level1-public-surface-observation-human-action-completion-recovery-decision-recovery-execution-readiness-remediation-execution-authority-binding-request.json","utf8"));

assert.equal(a.program_number,167);
assert.equal(a.status,"LEVEL1_PUBLIC_SURFACE_OBSERVATION_HUMAN_ACTION_COMPLETION_RECOVERY_DECISION_RECOVERY_EXECUTION_READINESS_REMEDIATION_EXECUTION_AUTHORITY_BINDING_REQUESTED_PENDING_AUTHORITY_BINDING_RECEIPT");

assert.equal(a.level3_axis.principle,"remediation_execution_authority_binding_request_is_not_binding_receipt_or_remediation_execution");
assert.equal(a.level3_axis.readiness_gate_passed,false);
assert.equal(a.level3_axis.readiness_remediation_plan_validated,true);
assert.equal(a.level3_axis.readiness_remediation_execution_request_validated,true);
assert.equal(a.level3_axis.remediation_execution_authority_binding_required,true);
assert.equal(a.level3_axis.remediation_execution_authority_binding_requested,true);
assert.equal(a.level3_axis.remediation_execution_authority_binding_receipt_received,false);
assert.equal(a.level3_axis.remediation_execution_authority_binding_validated,false);
assert.equal(a.level3_axis.remediation_execution_authority_binding_completed,false);
assert.equal(a.level3_axis.readiness_remediation_execution_authorized,false);
assert.equal(a.level3_axis.readiness_remediation_execution_performed,false);
assert.equal(a.level3_axis.launch_readiness_unlocked,false);
assert.equal(a.level3_axis.readiness_unlock_allowed,false);
assert.equal(a.level3_axis.legal_or_certification_effect,false);

assert.equal(a.human_decision_response.validated,true);
assert.equal(a.human_decision_response.authorization_effect,false);
assert.equal(a.human_decision_record.record_effect,"REMEDIATION_EXECUTION_AUTHORITY_BINDING_REQUESTED_PENDING_BINDING_RECEIPT");

assert.equal(a.readiness_remediation_execution_request.required,true);
assert.equal(a.readiness_remediation_execution_request.created,true);
assert.equal(a.readiness_remediation_execution_request.validated,true);
assert.equal(a.readiness_remediation_execution_request.authorized,false);
assert.equal(a.readiness_remediation_execution_request.requires_execution_authority_binding,true);
assert.equal(a.readiness_remediation_execution_request.does_not_authorize_execution,true);
assert.equal(a.readiness_remediation_execution_request.does_not_execute_remediation,true);

assert.equal(a.readiness_remediation_execution_authority_binding_request.required,true);
assert.equal(a.readiness_remediation_execution_authority_binding_request.created,true);
assert.equal(a.readiness_remediation_execution_authority_binding_request.requested,true);
assert.equal(a.readiness_remediation_execution_authority_binding_request.received,false);
assert.equal(a.readiness_remediation_execution_authority_binding_request.validated,false);
assert.equal(a.readiness_remediation_execution_authority_binding_request.completed,false);
assert.equal(a.readiness_remediation_execution_authority_binding_request.request_status,"REQUESTED_PENDING_REMEDIATION_EXECUTION_AUTHORITY_BINDING_RECEIPT");
assert.equal(a.readiness_remediation_execution_authority_binding_request.request_effect,"AUTHORITY_BINDING_REQUESTED_NO_RECEIPT_NO_VALIDATION_NO_AUTHORIZATION_NO_REMEDIATION_EXECUTION_NO_READINESS_UNLOCK");
assert.equal(a.readiness_remediation_execution_authority_binding_request.references_validated_remediation_execution_request,true);
assert.equal(a.readiness_remediation_execution_authority_binding_request.references_validated_remediation_plan,true);
assert.equal(a.readiness_remediation_execution_authority_binding_request.references_validated_no_go_decision,true);
assert.equal(a.readiness_remediation_execution_authority_binding_request.references_readiness_gate_validation,true);
assert.equal(a.readiness_remediation_execution_authority_binding_request.references_evidence_bundle,true);
assert.equal(a.readiness_remediation_execution_authority_binding_request.references_execution_closure,true);
assert.equal(a.readiness_remediation_execution_authority_binding_request.contains_human_authority_requirement,true);
assert.equal(a.readiness_remediation_execution_authority_binding_request.contains_policy_binding_requirement,true);
assert.equal(a.readiness_remediation_execution_authority_binding_request.contains_target_binding_requirement,true);
assert.equal(a.readiness_remediation_execution_authority_binding_request.contains_scope_binding_requirement,true);
assert.equal(a.readiness_remediation_execution_authority_binding_request.requires_binding_receipt,true);
assert.equal(a.readiness_remediation_execution_authority_binding_request.requires_binding_validation,true);
assert.equal(a.readiness_remediation_execution_authority_binding_request.requires_binding_completion,true);
assert.equal(a.readiness_remediation_execution_authority_binding_request.does_not_authorize_execution,true);
assert.equal(a.readiness_remediation_execution_authority_binding_request.does_not_execute_remediation,true);
assert.equal(a.readiness_remediation_execution_authority_binding_request.does_not_unlock_readiness,true);

assert.equal(a.readiness_remediation_execution_authority_binding_receipt.required,true);
assert.equal(a.readiness_remediation_execution_authority_binding_receipt.received,false);
assert.equal(a.readiness_remediation_execution_authority_binding_receipt.validated,false);
assert.equal(a.readiness_remediation_execution_authority_binding_receipt.receipt_status,"PENDING_REMEDIATION_EXECUTION_AUTHORITY_BINDING_RECEIPT");

assert.equal(a.readiness_remediation_execution_authority_binding.required,true);
assert.equal(a.readiness_remediation_execution_authority_binding.requested,true);
assert.equal(a.readiness_remediation_execution_authority_binding.received,false);
assert.equal(a.readiness_remediation_execution_authority_binding.validated,false);
assert.equal(a.readiness_remediation_execution_authority_binding.completed,false);
assert.equal(a.readiness_remediation_execution_authority_binding.binding_status,"REQUESTED_PENDING_REMEDIATION_EXECUTION_AUTHORITY_BINDING_RECEIPT");

assert.equal(a.readiness_remediation_execution.required,true);
assert.equal(a.readiness_remediation_execution.requested,true);
assert.equal(a.readiness_remediation_execution.request_validated,true);
assert.equal(a.readiness_remediation_execution.authority_binding_requested,true);
assert.equal(a.readiness_remediation_execution.authority_binding_received,false);
assert.equal(a.readiness_remediation_execution.authority_binding_validated,false);
assert.equal(a.readiness_remediation_execution.authority_binding_completed,false);
assert.equal(a.readiness_remediation_execution.authorized,false);
assert.equal(a.readiness_remediation_execution.performed,false);
assert.equal(a.readiness_remediation_execution.execution_status,"PENDING_REMEDIATION_EXECUTION_AUTHORITY_BINDING_RECEIPT");

assert.equal(a.recovery_execution.readiness_remediation_execution_requested,true);
assert.equal(a.recovery_execution.readiness_remediation_execution_request_validated,true);
assert.equal(a.recovery_execution.readiness_remediation_execution_authority_binding_requested,true);
assert.equal(a.recovery_execution.readiness_remediation_execution_authority_binding_received,false);
assert.equal(a.recovery_execution.readiness_remediation_execution_authority_binding_validated,false);
assert.equal(a.recovery_execution.readiness_remediation_execution_authority_binding_completed,false);
assert.equal(a.recovery_execution.readiness_remediation_execution_authorized,false);
assert.equal(a.recovery_execution.readiness_remediation_execution_performed,false);
assert.equal(a.recovery_execution.readiness_gate_passed,false);
assert.equal(a.recovery_execution.pending,"READINESS_REMEDIATION_EXECUTION_AUTHORITY_BINDING_RECEIPT");

assert.equal(a.readiness.external_customer_ready,false);
assert.equal(a.readiness.banking_pack_ready,false);
assert.equal(a.readiness.level1_launch_ready,false);
assert.equal(a.readiness.production_ready,false);

assert.equal(a.authority.ai_authority_allowed,false);
assert.equal(a.authority.legal_validity_claimed,false);
assert.equal(a.authority.accreditation_claimed,false);
assert.equal(a.authority.procurement_eligibility_claimed,false);

assert.equal(a.constraints.no_readiness_unlock,true);
assert.equal(a.constraints.no_ai_authority,true);
assert.equal(a.constraints.no_legal_validity,true);
assert.equal(a.constraints.no_accreditation,true);
assert.equal(a.constraints.no_procurement_eligibility,true);
assert.equal(a.constraints.no_certification_claim,true);
assert.equal(a.constraints.no_product_claim,true);
assert.equal(a.constraints.no_launch_claim,true);
assert.equal(a.constraints.no_readiness_gate_pass_claim,true);
assert.equal(a.constraints.no_production_readiness_claim,true);
assert.equal(a.constraints.no_remediation_execution_claim,true);
assert.equal(a.constraints.no_remediation_execution_authority_binding_receipt_claim,true);
assert.equal(a.constraints.no_remediation_execution_authority_binding_validation_claim,true);
assert.equal(a.constraints.no_remediation_execution_authorization_claim,true);

assert.equal(a.previous_program,"PROG-166");
assert.equal(a.next_required_program,"PROG-168-HBCE-LEVEL1-PUBLIC-SURFACE-OBSERVATION-HUMAN-ACTION-COMPLETION-RECOVERY-DECISION-RECOVERY-EXECUTION-READINESS-REMEDIATION-EXECUTION-AUTHORITY-BINDING-RECEIPT");

console.log("PROG_167_TEST=PASS");
