const fs=require("fs"),assert=require("assert/strict");
const a=JSON.parse(fs.readFileSync("docs/launch/level1/prog-169-level1-public-surface-observation-human-action-completion-recovery-decision-recovery-execution-readiness-remediation-execution-authority-binding-validation.json","utf8"));

assert.equal(a.program_number,169);
assert.equal(a.status,"LEVEL1_PUBLIC_SURFACE_OBSERVATION_HUMAN_ACTION_COMPLETION_RECOVERY_DECISION_RECOVERY_EXECUTION_READINESS_REMEDIATION_EXECUTION_AUTHORITY_BINDING_VALIDATED_PENDING_AUTHORITY_BINDING_COMPLETION");

assert.equal(a.level3_axis.principle,"validated_remediation_execution_authority_binding_is_not_binding_completion_or_remediation_execution");
assert.equal(a.level3_axis.readiness_gate_passed,false);
assert.equal(a.level3_axis.readiness_remediation_plan_validated,true);
assert.equal(a.level3_axis.readiness_remediation_execution_request_validated,true);
assert.equal(a.level3_axis.remediation_execution_authority_binding_requested,true);
assert.equal(a.level3_axis.remediation_execution_authority_binding_receipt_received,true);
assert.equal(a.level3_axis.remediation_execution_authority_binding_receipt_validated,true);
assert.equal(a.level3_axis.remediation_execution_authority_binding_validated,true);
assert.equal(a.level3_axis.remediation_execution_authority_binding_completed,false);
assert.equal(a.level3_axis.readiness_remediation_execution_authorized,false);
assert.equal(a.level3_axis.readiness_remediation_execution_performed,false);
assert.equal(a.level3_axis.launch_readiness_unlocked,false);
assert.equal(a.level3_axis.readiness_unlock_allowed,false);
assert.equal(a.level3_axis.legal_or_certification_effect,false);

assert.equal(a.human_decision_response.validated,true);
assert.equal(a.human_decision_response.authorization_effect,false);
assert.equal(a.human_decision_record.record_effect,"REMEDIATION_EXECUTION_AUTHORITY_BINDING_VALIDATED_PENDING_BINDING_COMPLETION");

assert.equal(a.readiness_remediation_execution_authority_binding_request.required,true);
assert.equal(a.readiness_remediation_execution_authority_binding_request.created,true);
assert.equal(a.readiness_remediation_execution_authority_binding_request.requested,true);
assert.equal(a.readiness_remediation_execution_authority_binding_request.received,true);
assert.equal(a.readiness_remediation_execution_authority_binding_request.validated,true);
assert.equal(a.readiness_remediation_execution_authority_binding_request.completed,false);
assert.equal(a.readiness_remediation_execution_authority_binding_request.request_status,"VALIDATED_PENDING_REMEDIATION_EXECUTION_AUTHORITY_BINDING_COMPLETION");
assert.equal(a.readiness_remediation_execution_authority_binding_request.does_not_complete_binding,true);
assert.equal(a.readiness_remediation_execution_authority_binding_request.does_not_authorize_execution,true);
assert.equal(a.readiness_remediation_execution_authority_binding_request.does_not_execute_remediation,true);
assert.equal(a.readiness_remediation_execution_authority_binding_request.does_not_unlock_readiness,true);

assert.equal(a.readiness_remediation_execution_authority_binding_receipt.required,true);
assert.equal(a.readiness_remediation_execution_authority_binding_receipt.received,true);
assert.equal(a.readiness_remediation_execution_authority_binding_receipt.validated,true);
assert.equal(a.readiness_remediation_execution_authority_binding_receipt.receipt_status,"VALIDATED");
assert.equal(a.readiness_remediation_execution_authority_binding_receipt.receipt_effect,"AUTHORITY_BINDING_RECEIPT_VALIDATED_NO_BINDING_COMPLETION_NO_AUTHORIZATION_NO_REMEDIATION_EXECUTION_NO_READINESS_UNLOCK");
assert.equal(a.readiness_remediation_execution_authority_binding_receipt.requires_binding_completion,true);
assert.equal(a.readiness_remediation_execution_authority_binding_receipt.does_not_complete_binding,true);
assert.equal(a.readiness_remediation_execution_authority_binding_receipt.does_not_authorize_execution,true);
assert.equal(a.readiness_remediation_execution_authority_binding_receipt.does_not_execute_remediation,true);
assert.equal(a.readiness_remediation_execution_authority_binding_receipt.does_not_unlock_readiness,true);

assert.equal(a.readiness_remediation_execution_authority_binding_validation.required,true);
assert.equal(a.readiness_remediation_execution_authority_binding_validation.performed,true);
assert.equal(a.readiness_remediation_execution_authority_binding_validation.validated,true);
assert.equal(a.readiness_remediation_execution_authority_binding_validation.completed,false);
assert.equal(a.readiness_remediation_execution_authority_binding_validation.authority_identity_validated,true);
assert.equal(a.readiness_remediation_execution_authority_binding_validation.policy_binding_validated,true);
assert.equal(a.readiness_remediation_execution_authority_binding_validation.target_binding_validated,true);
assert.equal(a.readiness_remediation_execution_authority_binding_validation.scope_binding_validated,true);
assert.equal(a.readiness_remediation_execution_authority_binding_validation.receipt_integrity_validated,true);
assert.equal(a.readiness_remediation_execution_authority_binding_validation.validated_request_reference_validated,true);
assert.equal(a.readiness_remediation_execution_authority_binding_validation.validated_remediation_plan_reference_validated,true);
assert.equal(a.readiness_remediation_execution_authority_binding_validation.validated_no_go_decision_reference_validated,true);
assert.equal(a.readiness_remediation_execution_authority_binding_validation.evidence_bundle_reference_validated,true);
assert.equal(a.readiness_remediation_execution_authority_binding_validation.execution_closure_reference_validated,true);
assert.equal(a.readiness_remediation_execution_authority_binding_validation.human_authority_requirement_present,true);
assert.equal(a.readiness_remediation_execution_authority_binding_validation.no_readiness_unlock_constraint_validated,true);
assert.equal(a.readiness_remediation_execution_authority_binding_validation.no_product_claim_constraint_validated,true);
assert.equal(a.readiness_remediation_execution_authority_binding_validation.no_launch_claim_constraint_validated,true);
assert.equal(a.readiness_remediation_execution_authority_binding_validation.validation_status,"VALIDATED_PENDING_REMEDIATION_EXECUTION_AUTHORITY_BINDING_COMPLETION");
assert.equal(a.readiness_remediation_execution_authority_binding_validation.does_not_complete_binding,true);
assert.equal(a.readiness_remediation_execution_authority_binding_validation.does_not_authorize_execution,true);
assert.equal(a.readiness_remediation_execution_authority_binding_validation.does_not_execute_remediation,true);
assert.equal(a.readiness_remediation_execution_authority_binding_validation.does_not_unlock_readiness,true);

assert.equal(a.readiness_remediation_execution_authority_binding.required,true);
assert.equal(a.readiness_remediation_execution_authority_binding.requested,true);
assert.equal(a.readiness_remediation_execution_authority_binding.received,true);
assert.equal(a.readiness_remediation_execution_authority_binding.receipt_received,true);
assert.equal(a.readiness_remediation_execution_authority_binding.receipt_validated,true);
assert.equal(a.readiness_remediation_execution_authority_binding.validated,true);
assert.equal(a.readiness_remediation_execution_authority_binding.completed,false);
assert.equal(a.readiness_remediation_execution_authority_binding.binding_status,"VALIDATED_PENDING_REMEDIATION_EXECUTION_AUTHORITY_BINDING_COMPLETION");

assert.equal(a.readiness_remediation_execution.required,true);
assert.equal(a.readiness_remediation_execution.requested,true);
assert.equal(a.readiness_remediation_execution.request_validated,true);
assert.equal(a.readiness_remediation_execution.authority_binding_requested,true);
assert.equal(a.readiness_remediation_execution.authority_binding_received,true);
assert.equal(a.readiness_remediation_execution.authority_binding_receipt_received,true);
assert.equal(a.readiness_remediation_execution.authority_binding_receipt_validated,true);
assert.equal(a.readiness_remediation_execution.authority_binding_validated,true);
assert.equal(a.readiness_remediation_execution.authority_binding_completed,false);
assert.equal(a.readiness_remediation_execution.authorized,false);
assert.equal(a.readiness_remediation_execution.performed,false);
assert.equal(a.readiness_remediation_execution.execution_status,"PENDING_REMEDIATION_EXECUTION_AUTHORITY_BINDING_COMPLETION");

assert.equal(a.recovery_execution.readiness_remediation_execution_requested,true);
assert.equal(a.recovery_execution.readiness_remediation_execution_request_validated,true);
assert.equal(a.recovery_execution.readiness_remediation_execution_authority_binding_requested,true);
assert.equal(a.recovery_execution.readiness_remediation_execution_authority_binding_received,true);
assert.equal(a.recovery_execution.readiness_remediation_execution_authority_binding_receipt_received,true);
assert.equal(a.recovery_execution.readiness_remediation_execution_authority_binding_receipt_validated,true);
assert.equal(a.recovery_execution.readiness_remediation_execution_authority_binding_validated,true);
assert.equal(a.recovery_execution.readiness_remediation_execution_authority_binding_completed,false);
assert.equal(a.recovery_execution.readiness_remediation_execution_authorized,false);
assert.equal(a.recovery_execution.readiness_remediation_execution_performed,false);
assert.equal(a.recovery_execution.readiness_gate_passed,false);
assert.equal(a.recovery_execution.pending,"READINESS_REMEDIATION_EXECUTION_AUTHORITY_BINDING_COMPLETION");

assert.equal(a.readiness.external_customer_ready,false);
assert.equal(a.readiness.banking_pack_ready,false);
assert.equal(a.readiness.level1_launch_ready,false);
assert.equal(a.readiness.production_ready,false);

assert.equal(a.authority.ai_authority_allowed,false);
assert.equal(a.authority.legal_validity_claimed,false);
assert.equal(a.authority.accreditation_claimed,false);
assert.equal(a.authority.procurement_eligibility_claimed,false);

assert.equal(a.constraints.no_readiness_unlock,true);
assert.equal(a.constraints.no_ai_authority,true);
assert.equal(a.constraints.no_legal_validity,true);
assert.equal(a.constraints.no_accreditation,true);
assert.equal(a.constraints.no_procurement_eligibility,true);
assert.equal(a.constraints.no_certification_claim,true);
assert.equal(a.constraints.no_product_claim,true);
assert.equal(a.constraints.no_launch_claim,true);
assert.equal(a.constraints.no_readiness_gate_pass_claim,true);
assert.equal(a.constraints.no_production_readiness_claim,true);
assert.equal(a.constraints.no_remediation_execution_claim,true);
assert.equal(a.constraints.no_remediation_execution_authority_binding_completion_claim,true);
assert.equal(a.constraints.no_remediation_execution_authorization_claim,true);

assert.equal(a.previous_program,"PROG-168");
assert.equal(a.next_required_program,"PROG-170-HBCE-LEVEL1-PUBLIC-SURFACE-OBSERVATION-HUMAN-ACTION-COMPLETION-RECOVERY-DECISION-RECOVERY-EXECUTION-READINESS-REMEDIATION-EXECUTION-AUTHORITY-BINDING-COMPLETION");

console.log("PROG_169_TEST=PASS");
