const fs=require("fs"),assert=require("assert/strict");
const a=JSON.parse(fs.readFileSync("docs/launch/level1/prog-170-level1-public-surface-observation-human-action-completion-recovery-decision-recovery-execution-readiness-remediation-execution-authority-binding-completion.json","utf8"));

assert.equal(a.program_number,170);
assert.equal(a.status,"LEVEL1_PUBLIC_SURFACE_OBSERVATION_HUMAN_ACTION_COMPLETION_RECOVERY_DECISION_RECOVERY_EXECUTION_READINESS_REMEDIATION_EXECUTION_AUTHORITY_BINDING_COMPLETED_PENDING_REMEDIATION_EXECUTION_PRECOMMIT_GATE");

assert.equal(a.level3_axis.principle,"completed_remediation_execution_authority_binding_is_not_precommit_or_remediation_execution");
assert.equal(a.level3_axis.readiness_gate_passed,false);
assert.equal(a.level3_axis.readiness_remediation_plan_validated,true);
assert.equal(a.level3_axis.readiness_remediation_execution_request_validated,true);
assert.equal(a.level3_axis.remediation_execution_authority_binding_requested,true);
assert.equal(a.level3_axis.remediation_execution_authority_binding_receipt_received,true);
assert.equal(a.level3_axis.remediation_execution_authority_binding_receipt_validated,true);
assert.equal(a.level3_axis.remediation_execution_authority_binding_validated,true);
assert.equal(a.level3_axis.remediation_execution_authority_binding_completed,true);
assert.equal(a.level3_axis.remediation_execution_precommit_gate_required,true);
assert.equal(a.level3_axis.remediation_execution_precommit_gate_passed,false);
assert.equal(a.level3_axis.remediation_execution_precommit_committed,false);
assert.equal(a.level3_axis.readiness_remediation_execution_authorized,false);
assert.equal(a.level3_axis.readiness_remediation_execution_performed,false);
assert.equal(a.level3_axis.launch_readiness_unlocked,false);
assert.equal(a.level3_axis.readiness_unlock_allowed,false);
assert.equal(a.level3_axis.legal_or_certification_effect,false);

assert.equal(a.human_decision_response.validated,true);
assert.equal(a.human_decision_response.authorization_effect,false);
assert.equal(a.human_decision_record.record_effect,"REMEDIATION_EXECUTION_AUTHORITY_BINDING_COMPLETED_PENDING_PRECOMMIT_GATE");

assert.equal(a.readiness_remediation_execution_authority_binding_request.required,true);
assert.equal(a.readiness_remediation_execution_authority_binding_request.created,true);
assert.equal(a.readiness_remediation_execution_authority_binding_request.requested,true);
assert.equal(a.readiness_remediation_execution_authority_binding_request.received,true);
assert.equal(a.readiness_remediation_execution_authority_binding_request.validated,true);
assert.equal(a.readiness_remediation_execution_authority_binding_request.completed,true);
assert.equal(a.readiness_remediation_execution_authority_binding_request.request_status,"COMPLETED_PENDING_REMEDIATION_EXECUTION_PRECOMMIT_GATE");
assert.equal(a.readiness_remediation_execution_authority_binding_request.does_not_pass_precommit_gate,true);
assert.equal(a.readiness_remediation_execution_authority_binding_request.does_not_authorize_execution,true);
assert.equal(a.readiness_remediation_execution_authority_binding_request.does_not_execute_remediation,true);
assert.equal(a.readiness_remediation_execution_authority_binding_request.does_not_unlock_readiness,true);

assert.equal(a.readiness_remediation_execution_authority_binding_receipt.required,true);
assert.equal(a.readiness_remediation_execution_authority_binding_receipt.received,true);
assert.equal(a.readiness_remediation_execution_authority_binding_receipt.validated,true);
assert.equal(a.readiness_remediation_execution_authority_binding_receipt.binding_completed,true);
assert.equal(a.readiness_remediation_execution_authority_binding_receipt.requires_precommit_gate,true);
assert.equal(a.readiness_remediation_execution_authority_binding_receipt.does_not_pass_precommit_gate,true);
assert.equal(a.readiness_remediation_execution_authority_binding_receipt.does_not_authorize_execution,true);
assert.equal(a.readiness_remediation_execution_authority_binding_receipt.does_not_execute_remediation,true);
assert.equal(a.readiness_remediation_execution_authority_binding_receipt.does_not_unlock_readiness,true);

assert.equal(a.readiness_remediation_execution_authority_binding_validation.required,true);
assert.equal(a.readiness_remediation_execution_authority_binding_validation.performed,true);
assert.equal(a.readiness_remediation_execution_authority_binding_validation.validated,true);
assert.equal(a.readiness_remediation_execution_authority_binding_validation.completed,true);
assert.equal(a.readiness_remediation_execution_authority_binding_validation.validation_status,"COMPLETED_PENDING_REMEDIATION_EXECUTION_PRECOMMIT_GATE");
assert.equal(a.readiness_remediation_execution_authority_binding_validation.does_not_pass_precommit_gate,true);
assert.equal(a.readiness_remediation_execution_authority_binding_validation.does_not_authorize_execution,true);
assert.equal(a.readiness_remediation_execution_authority_binding_validation.does_not_execute_remediation,true);
assert.equal(a.readiness_remediation_execution_authority_binding_validation.does_not_unlock_readiness,true);

assert.equal(a.readiness_remediation_execution_authority_binding.required,true);
assert.equal(a.readiness_remediation_execution_authority_binding.requested,true);
assert.equal(a.readiness_remediation_execution_authority_binding.received,true);
assert.equal(a.readiness_remediation_execution_authority_binding.receipt_received,true);
assert.equal(a.readiness_remediation_execution_authority_binding.receipt_validated,true);
assert.equal(a.readiness_remediation_execution_authority_binding.validated,true);
assert.equal(a.readiness_remediation_execution_authority_binding.completed,true);
assert.equal(a.readiness_remediation_execution_authority_binding.binding_status,"COMPLETED_PENDING_REMEDIATION_EXECUTION_PRECOMMIT_GATE");
assert.equal(a.readiness_remediation_execution_authority_binding.does_not_pass_precommit_gate,true);
assert.equal(a.readiness_remediation_execution_authority_binding.does_not_authorize_execution,true);
assert.equal(a.readiness_remediation_execution_authority_binding.does_not_execute_remediation,true);
assert.equal(a.readiness_remediation_execution_authority_binding.does_not_unlock_readiness,true);

assert.equal(a.readiness_remediation_execution_precommit_gate.required,true);
assert.equal(a.readiness_remediation_execution_precommit_gate.defined,true);
assert.equal(a.readiness_remediation_execution_precommit_gate.evaluated,false);
assert.equal(a.readiness_remediation_execution_precommit_gate.passed,false);
assert.equal(a.readiness_remediation_execution_precommit_gate.gate_status,"PENDING_REMEDIATION_EXECUTION_PRECOMMIT_GATE");

assert.equal(a.readiness_remediation_execution_precommit.required,true);
assert.equal(a.readiness_remediation_execution_precommit.prepared,false);
assert.equal(a.readiness_remediation_execution_precommit.committed,false);
assert.equal(a.readiness_remediation_execution_precommit.precommit_status,"PENDING_REMEDIATION_EXECUTION_PRECOMMIT_GATE");

assert.equal(a.readiness_remediation_execution.required,true);
assert.equal(a.readiness_remediation_execution.requested,true);
assert.equal(a.readiness_remediation_execution.request_validated,true);
assert.equal(a.readiness_remediation_execution.authority_binding_requested,true);
assert.equal(a.readiness_remediation_execution.authority_binding_received,true);
assert.equal(a.readiness_remediation_execution.authority_binding_receipt_received,true);
assert.equal(a.readiness_remediation_execution.authority_binding_receipt_validated,true);
assert.equal(a.readiness_remediation_execution.authority_binding_validated,true);
assert.equal(a.readiness_remediation_execution.authority_binding_completed,true);
assert.equal(a.readiness_remediation_execution.precommit_gate_required,true);
assert.equal(a.readiness_remediation_execution.precommit_gate_passed,false);
assert.equal(a.readiness_remediation_execution.precommit_committed,false);
assert.equal(a.readiness_remediation_execution.authorized,false);
assert.equal(a.readiness_remediation_execution.performed,false);
assert.equal(a.readiness_remediation_execution.execution_status,"PENDING_REMEDIATION_EXECUTION_PRECOMMIT_GATE");

assert.equal(a.recovery_execution.readiness_remediation_execution_requested,true);
assert.equal(a.recovery_execution.readiness_remediation_execution_request_validated,true);
assert.equal(a.recovery_execution.readiness_remediation_execution_authority_binding_requested,true);
assert.equal(a.recovery_execution.readiness_remediation_execution_authority_binding_received,true);
assert.equal(a.recovery_execution.readiness_remediation_execution_authority_binding_receipt_received,true);
assert.equal(a.recovery_execution.readiness_remediation_execution_authority_binding_receipt_validated,true);
assert.equal(a.recovery_execution.readiness_remediation_execution_authority_binding_validated,true);
assert.equal(a.recovery_execution.readiness_remediation_execution_authority_binding_completed,true);
assert.equal(a.recovery_execution.readiness_remediation_execution_precommit_gate_required,true);
assert.equal(a.recovery_execution.readiness_remediation_execution_precommit_gate_passed,false);
assert.equal(a.recovery_execution.readiness_remediation_execution_precommit_committed,false);
assert.equal(a.recovery_execution.readiness_remediation_execution_authorized,false);
assert.equal(a.recovery_execution.readiness_remediation_execution_performed,false);
assert.equal(a.recovery_execution.readiness_gate_passed,false);
assert.equal(a.recovery_execution.pending,"READINESS_REMEDIATION_EXECUTION_PRECOMMIT_GATE");

assert.equal(a.readiness.external_customer_ready,false);
assert.equal(a.readiness.banking_pack_ready,false);
assert.equal(a.readiness.level1_launch_ready,false);
assert.equal(a.readiness.production_ready,false);

assert.equal(a.authority.ai_authority_allowed,false);
assert.equal(a.authority.legal_validity_claimed,false);
assert.equal(a.authority.accreditation_claimed,false);
assert.equal(a.authority.procurement_eligibility_claimed,false);

assert.equal(a.constraints.no_readiness_unlock,true);
assert.equal(a.constraints.no_ai_authority,true);
assert.equal(a.constraints.no_legal_validity,true);
assert.equal(a.constraints.no_accreditation,true);
assert.equal(a.constraints.no_procurement_eligibility,true);
assert.equal(a.constraints.no_certification_claim,true);
assert.equal(a.constraints.no_product_claim,true);
assert.equal(a.constraints.no_launch_claim,true);
assert.equal(a.constraints.no_readiness_gate_pass_claim,true);
assert.equal(a.constraints.no_production_readiness_claim,true);
assert.equal(a.constraints.no_remediation_execution_claim,true);
assert.equal(a.constraints.no_remediation_execution_precommit_claim,true);
assert.equal(a.constraints.no_remediation_execution_authorization_claim,true);

assert.equal(a.previous_program,"PROG-169");
assert.equal(a.next_required_program,"PROG-171-HBCE-LEVEL1-PUBLIC-SURFACE-OBSERVATION-HUMAN-ACTION-COMPLETION-RECOVERY-DECISION-RECOVERY-EXECUTION-READINESS-REMEDIATION-EXECUTION-PRECOMMIT-GATE");

console.log("PROG_170_TEST=PASS");
