'use strict';

const assert = require('assert');

const {
  createExternalReviewCandidateEvidencePackRuntimeReadAccessDecisionReviewPackageExportSurfaceAccessDecisionReviewPackage,
  HBCE_EXTERNAL_REVIEW_CANDIDATE_EVIDENCE_PACK_RUNTIME_READ_ACCESS_DECISION_REVIEW_PACKAGE_EXPORT_SURFACE_ACCESS_DECISION_REVIEW_PACKAGE_PROTO,
  HBCE_EXTERNAL_REVIEW_CANDIDATE_EVIDENCE_PACK_RUNTIME_READ_ACCESS_DECISION_REVIEW_PACKAGE_EXPORT_SURFACE_ACCESS_DECISION_REVIEW_PACKAGE_KIND,
  HBCE_EXTERNAL_REVIEW_CANDIDATE_EVIDENCE_PACK_RUNTIME_READ_ACCESS_DECISION_REVIEW_PACKAGE_EXPORT_SURFACE_ACCESS_DECISION_REVIEW_PACKAGE_STATE
} = require('../../runtime/external-review/create-external-review-candidate-evidence-pack-runtime-read-access-decision-review-package-export-surface-access-decision-review-package');

const {
  createExternalReviewCandidateEvidencePackRuntimeReadAccessDecisionReviewPackageExportSurfaceAccessDecisionAuditIndex
} = require('../../runtime/external-review/create-external-review-candidate-evidence-pack-runtime-read-access-decision-review-package-export-surface-access-decision-audit-index');

function clone(value) {
  return JSON.parse(JSON.stringify(value));
}

const actual = createExternalReviewCandidateEvidencePackRuntimeReadAccessDecisionReviewPackageExportSurfaceAccessDecisionReviewPackage();
const body =
  actual.evidence_pack_runtime_read_access_decision_review_package_export_surface_access_decision_review_package;
const payload = body.review_package_payload;

assert.equal(actual.state, HBCE_EXTERNAL_REVIEW_CANDIDATE_EVIDENCE_PACK_RUNTIME_READ_ACCESS_DECISION_REVIEW_PACKAGE_EXPORT_SURFACE_ACCESS_DECISION_REVIEW_PACKAGE_STATE.READY);
assert.equal(actual.reason, 'HBCE_EXTERNAL_REVIEW_CANDIDATE_EVIDENCE_PACK_RUNTIME_READ_ACCESS_DECISION_REVIEW_PACKAGE_EXPORT_SURFACE_ACCESS_DECISION_REVIEW_PACKAGE_READY');
assert.equal(body.proto, HBCE_EXTERNAL_REVIEW_CANDIDATE_EVIDENCE_PACK_RUNTIME_READ_ACCESS_DECISION_REVIEW_PACKAGE_EXPORT_SURFACE_ACCESS_DECISION_REVIEW_PACKAGE_PROTO);
assert.equal(body.kind, HBCE_EXTERNAL_REVIEW_CANDIDATE_EVIDENCE_PACK_RUNTIME_READ_ACCESS_DECISION_REVIEW_PACKAGE_EXPORT_SURFACE_ACCESS_DECISION_REVIEW_PACKAGE_KIND);
assert.match(
  body.evidence_pack_runtime_read_access_decision_review_package_export_surface_access_decision_review_package_sha256,
  /^[a-f0-9]{64}$/
);
console.log('PASS HBCE_EXTERNAL_REVIEW_CANDIDATE_EVIDENCE_PACK_RUNTIME_READ_ACCESS_DECISION_REVIEW_PACKAGE_EXPORT_SURFACE_ACCESS_DECISION_REVIEW_PACKAGE_READY');

assert.equal(body.review_package_main_commit, '2d6c590d918bc4875075d93590d02bbe8bff5671');
assert.equal(body.source_audit_index_feature_commit, '4791b9cc796cf3570460f7e2af08872530608666');
assert.equal(body.source_audit_index_merge_commit, 'fa516944b045ec3916422bfed6eb0202659048ea');
assert.equal(body.source_audit_index_checkpoint_commit, '77637de6f9bd6e8969fd334257ffaaae8405d3cb');
assert.equal(body.source_audit_index_final_chain_audit_commit, '2d6c590d918bc4875075d93590d02bbe8bff5671');
assert.equal(body.source_audit_index_checkpoint_doc_sha256, 'dd97f1ecde32c6641c50c3f7c21de7e5baa57f4617aee3fbb1ea5d3b0362ff10');
assert.equal(body.source_final_chain_audit_doc_sha256, 'd119fd0bd1e8cae79696b463b3cc5ba0c86e41c279622c5fe9cf1ad09e189b9e');
console.log('PASS HBCE_EXTERNAL_REVIEW_CANDIDATE_EVIDENCE_PACK_RUNTIME_READ_ACCESS_DECISION_REVIEW_PACKAGE_EXPORT_SURFACE_ACCESS_DECISION_REVIEW_PACKAGE_SOURCE_AUDIT_INDEX');

assert.equal(body.source_audit_index_sha256, '6ed9890b47a6b94109ba4b657770e4f89cb2baa077bb22df535c168e8fb3e0e4');
assert.equal(body.source_audit_index_payload_sha256, 'e3b7b88886ff62ecaeac87e2c7c02341bc6e99c1d08123a7828cfba094e185ee');
assert.equal(payload.source_audit_index_sha256, body.source_audit_index_sha256);
assert.equal(payload.source_audit_index_payload_sha256, body.source_audit_index_payload_sha256);
assert.equal(payload.review_package_payload_sha256, body.review_package_payload_sha256);
console.log('PASS HBCE_EXTERNAL_REVIEW_CANDIDATE_EVIDENCE_PACK_RUNTIME_READ_ACCESS_DECISION_REVIEW_PACKAGE_EXPORT_SURFACE_ACCESS_DECISION_REVIEW_PACKAGE_HASHES');

assert.equal(body.review_package_scope, 'INTERNAL_RUNTIME_READ_ACCESS_DECISION_REVIEW_PACKAGE_EXPORT_SURFACE_ACCESS_DECISION_REVIEW_PACKAGE_ONLY');
assert.equal(body.review_package_consumer, 'JOKER_C2');
assert.equal(body.review_package_category, 'REVIEW_PACKAGE');
assert.equal(body.review_package_subcategory, 'RUNTIME_READ_ACCESS_DECISION_REVIEW_PACKAGE_EXPORT_SURFACE_ACCESS_DECISION_REVIEW_PACKAGE');
assert.equal(body.review_package_sections_satisfied, true);
assert.equal(body.observe_only_review_package_semantics, true);
assert.equal(payload.review_package_classification.decision_effect, 'OBSERVE_ONLY');
console.log('PASS HBCE_EXTERNAL_REVIEW_CANDIDATE_EVIDENCE_PACK_RUNTIME_READ_ACCESS_DECISION_REVIEW_PACKAGE_EXPORT_SURFACE_ACCESS_DECISION_REVIEW_PACKAGE_RECORD');

assert.equal(payload.review_package_sections.length, 5);
assert.equal(payload.review_package_sections[0].section_type, 'SOURCE_AUDIT_INDEX');
assert.equal(payload.review_package_sections[1].section_type, 'SOURCE_AUDIT_MANIFEST');
assert.equal(payload.review_package_sections[2].section_type, 'SOURCE_AUDIT_EVENT');
assert.equal(payload.review_package_sections[3].section_type, 'SOURCE_BOUNDARY_SNAPSHOT');
assert.equal(payload.review_package_sections[4].section_type, 'SOURCE_CAPABILITY_BINDING_SNAPSHOT');
assert.equal(payload.review_package_sections[0].section_observe_only, true);
assert.equal(payload.review_package_sections[1].section_access_granted, false);
assert.equal(payload.review_package_sections[2].section_access_granted, false);
console.log('PASS HBCE_EXTERNAL_REVIEW_CANDIDATE_EVIDENCE_PACK_RUNTIME_READ_ACCESS_DECISION_REVIEW_PACKAGE_EXPORT_SURFACE_ACCESS_DECISION_REVIEW_PACKAGE_SECTIONS');

assert.equal(body.authority_resolution_state, 'VALID');
assert.equal(body.policy_decision, 'UNEVALUATED');
assert.equal(body.policy_decision_reason, 'POLICY_EVALUATION_DEFERRED');
assert.equal(body.authorization_state, 'UNRESOLVED');
assert.equal(body.authorization_reason, 'POLICY_NOT_RESOLVED');
assert.equal(body.positive_allow_probe_authorization_state, 'UNRESOLVED');
assert.equal(payload.decision_snapshot.access_granted, false);
assert.equal(payload.decision_snapshot.creates_dispatch, false);
console.log('PASS HBCE_EXTERNAL_REVIEW_CANDIDATE_EVIDENCE_PACK_RUNTIME_READ_ACCESS_DECISION_REVIEW_PACKAGE_EXPORT_SURFACE_ACCESS_DECISION_REVIEW_PACKAGE_DECISION_SNAPSHOT');

assert.equal(payload.source_audit_index_scope, 'INTERNAL_RUNTIME_READ_ACCESS_DECISION_REVIEW_PACKAGE_EXPORT_SURFACE_ACCESS_DECISION_AUDIT_INDEX_ONLY');
assert.equal(payload.source_audit_index_consumer, 'JOKER_C2');
assert.equal(payload.source_audit_index_observe_only, true);
assert.equal(payload.source_index_entries_satisfied, true);
assert.equal(payload.source_manifest_entries_satisfied, true);
assert.equal(payload.source_access_granted, false);
assert.equal(payload.source_grants_authorization, false);
assert.equal(payload.source_executes_runtime_action, false);
assert.equal(payload.source_creates_dispatch, false);
assert.equal(payload.source_mutates_runtime_state, false);
console.log('PASS HBCE_EXTERNAL_REVIEW_CANDIDATE_EVIDENCE_PACK_RUNTIME_READ_ACCESS_DECISION_REVIEW_PACKAGE_EXPORT_SURFACE_ACCESS_DECISION_REVIEW_PACKAGE_SOURCE_AUDIT_INDEX_VIEW');

assert.equal(body.source_audit_manifest_sha256, '5ad5fcc305f928efda53c7e07cc2b6dc19c54a80d0b9e3eec96301342087ec5a');
assert.equal(body.source_audit_manifest_payload_sha256, 'c4a6aef21c78b0b198ac0e2396a2ca17bc5a4e220d1f7814fd278a8c7de522f0');
assert.equal(body.source_audit_event_sha256, '4fc422aca588cd1894fb089a0e2975c3404b2949da5855984b83aef0b5259c3e');
assert.equal(body.source_audit_event_payload_sha256, 'fca7ec5372660e985065eb16f8a3962e6dd2c9da9b187e3fd31d307c6099250d');
assert.equal(body.source_boundary_sha256, 'bf75c55f1a4cc1ffcc3d0e634426ccb9b2f2ce72983070002da569791fdb0274');
assert.equal(body.source_boundary_payload_sha256, '6da4f545dbae6a25e7ed8f30b2ed08f65e1c73ef56bf6594affa6388d8f27a11');
assert.equal(body.source_binding_sha256, 'cb0e03f17c9f144e284d2b5fbfb265617893991c7c7ecefef2294825f2eb2f4f');
assert.equal(body.source_index_sha256, '3f7c9aa821aac9f53e0ab0652a2cc235795059d55c9797ab32295508e7c7ed68');
assert.equal(body.source_surface_sha256, '57b0e3db62fe5354acf23b7f394feaf1bbc5197b51f9d9267d4cfe2a5c44fc1f');
assert.equal(body.source_export_sha256, 'aa63a1a9b35aba093831fd7938c323cef5830d893c215cd766c01a6fd8f4c0c4');
assert.equal(body.source_review_package_sha256, '86a19d81199457ecd6bc8f7d787862675f0403ddb6b34d73f17e8c35cc5b0bb5');
console.log('PASS HBCE_EXTERNAL_REVIEW_CANDIDATE_EVIDENCE_PACK_RUNTIME_READ_ACCESS_DECISION_REVIEW_PACKAGE_EXPORT_SURFACE_ACCESS_DECISION_REVIEW_PACKAGE_LINKAGE');

assert.equal(payload.stable_access_contract.deterministic_sha256_bound, true);
assert.equal(payload.stable_access_contract.source_audit_index_hash_bound, true);
assert.equal(payload.stable_access_contract.review_package_sections_satisfied, true);
assert.equal(payload.stable_access_contract.index_entries_satisfied, true);
assert.equal(payload.stable_access_contract.manifest_entries_satisfied, true);
assert.equal(payload.stable_access_contract.observe_only_review_package_semantics, true);
assert.equal(payload.stable_access_contract.review_package_does_not_authorize, true);
assert.equal(payload.stable_access_contract.review_package_does_not_dispatch, true);
assert.equal(payload.stable_access_contract.review_package_does_not_execute, true);
console.log('PASS HBCE_EXTERNAL_REVIEW_CANDIDATE_EVIDENCE_PACK_RUNTIME_READ_ACCESS_DECISION_REVIEW_PACKAGE_EXPORT_SURFACE_ACCESS_DECISION_REVIEW_PACKAGE_ACCESS_CONTRACT');

assert.equal(payload.assertions.review_package_does_not_authorize, true);
assert.equal(payload.assertions.review_package_does_not_dispatch, true);
assert.equal(payload.assertions.review_package_does_not_execute, true);
assert.equal(payload.assertions.no_authorization_artifact_created, true);
assert.equal(body.grants_authorization, false);
assert.equal(body.creates_authorization_artifact, false);
assert.equal(body.creates_dispatch, false);
console.log('PASS HBCE_EXTERNAL_REVIEW_CANDIDATE_EVIDENCE_PACK_RUNTIME_READ_ACCESS_DECISION_REVIEW_PACKAGE_EXPORT_SURFACE_ACCESS_DECISION_REVIEW_PACKAGE_NON_AUTHORIZATION');

assert.equal(body.access_granted, false);
assert.equal(body.grants_authorization, false);
assert.equal(body.creates_authorization_artifact, false);
assert.equal(body.executes_runtime_action, false);
assert.equal(body.creates_dispatch, false);
assert.equal(body.mutates_runtime_state, false);
assert.equal(body.runtime_audit_log_mutated, false);
assert.equal(body.external_audit_log_mutated, false);
console.log('PASS HBCE_EXTERNAL_REVIEW_CANDIDATE_EVIDENCE_PACK_RUNTIME_READ_ACCESS_DECISION_REVIEW_PACKAGE_EXPORT_SURFACE_ACCESS_DECISION_REVIEW_PACKAGE_READ_ONLY');

assert.equal(body.public_registry_mutated, false);
assert.equal(body.external_trust_registry_mutated, false);
assert.equal(body.legal_certification_created, false);
assert.equal(body.eidas_qualification_created, false);
assert.equal(body.opc_allow_created, false);
assert.equal(body.deployment_success_proven, false);
assert.equal(body.production_deployment_proven, false);
console.log('PASS HBCE_EXTERNAL_REVIEW_CANDIDATE_EVIDENCE_PACK_RUNTIME_READ_ACCESS_DECISION_REVIEW_PACKAGE_EXPORT_SURFACE_ACCESS_DECISION_REVIEW_PACKAGE_FALSE_EFFECTS');

assert.equal(body.external_review_execution_created, false);
assert.equal(body.external_review_opinion_created, false);
assert.equal(body.external_review_report_created, false);
assert.equal(body.external_review_submission_created, false);
assert.equal(body.external_review_publication_created, false);
assert.equal(payload.assertions.no_external_review_execution_created, true);
assert.equal(payload.assertions.no_external_review_submission_created, true);
assert.equal(payload.assertions.no_external_review_publication_created, true);
console.log('PASS HBCE_EXTERNAL_REVIEW_CANDIDATE_EVIDENCE_PACK_RUNTIME_READ_ACCESS_DECISION_REVIEW_PACKAGE_EXPORT_SURFACE_ACCESS_DECISION_REVIEW_PACKAGE_NO_EXTERNAL_REVIEW');

assert.equal(payload.review_package_view.source_audit_index_required, true);
assert.equal(payload.review_package_view.source_audit_index_hash_bound, true);
assert.equal(payload.review_package_view.review_package_sections_count, 5);
assert.equal(payload.review_package_view.review_package_sections_satisfied, true);
assert.equal(payload.review_package_view.index_entries_satisfied, true);
assert.equal(payload.review_package_view.manifest_entries_satisfied, true);
assert.equal(payload.review_package_view.runtime_state_mutated_by_review_package, false);
assert.equal(payload.review_package_view.external_review_triggered_by_review_package, false);
assert.equal(payload.assertions.review_package_sections_satisfied, true);
console.log('PASS HBCE_EXTERNAL_REVIEW_CANDIDATE_EVIDENCE_PACK_RUNTIME_READ_ACCESS_DECISION_REVIEW_PACKAGE_EXPORT_SURFACE_ACCESS_DECISION_REVIEW_PACKAGE_REVIEW_PACKAGE_SEMANTICS');

assert.equal(body.review_package_does_not_authorize, true);
assert.equal(body.observe_only_review_package_semantics, true);
assert.equal(payload.assertions.observe_only_review_package_semantics, true);
assert.equal(payload.assertions.observe_only_index_semantics_preserved, true);
assert.equal(payload.assertions.observe_only_manifest_semantics_preserved, true);
assert.equal(payload.assertions.append_only_source_event_preserved, true);
assert.equal(payload.assertions.canonical_json_object, true);
assert.equal(payload.assertions.deterministic_sha256_bound, true);
assert.equal(payload.readable_summary.legal_certification_created, false);
assert.equal(payload.readable_summary.eidas_qualification_created, false);
assert.equal(payload.readable_summary.opc_allow_created, false);
console.log('PASS HBCE_EXTERNAL_REVIEW_CANDIDATE_EVIDENCE_PACK_RUNTIME_READ_ACCESS_DECISION_REVIEW_PACKAGE_EXPORT_SURFACE_ACCESS_DECISION_REVIEW_PACKAGE_OBSERVE_ONLY_SEMANTICS');

const first = createExternalReviewCandidateEvidencePackRuntimeReadAccessDecisionReviewPackageExportSurfaceAccessDecisionReviewPackage();
const second = createExternalReviewCandidateEvidencePackRuntimeReadAccessDecisionReviewPackageExportSurfaceAccessDecisionReviewPackage();
assert.equal(
  first.evidence_pack_runtime_read_access_decision_review_package_export_surface_access_decision_review_package
    .evidence_pack_runtime_read_access_decision_review_package_export_surface_access_decision_review_package_sha256,
  second.evidence_pack_runtime_read_access_decision_review_package_export_surface_access_decision_review_package
    .evidence_pack_runtime_read_access_decision_review_package_export_surface_access_decision_review_package_sha256
);
assert.deepEqual(first, second);
console.log('PASS HBCE_EXTERNAL_REVIEW_CANDIDATE_EVIDENCE_PACK_RUNTIME_READ_ACCESS_DECISION_REVIEW_PACKAGE_EXPORT_SURFACE_ACCESS_DECISION_REVIEW_PACKAGE_DETERMINISTIC');

const invalidGeneratedAt = createExternalReviewCandidateEvidencePackRuntimeReadAccessDecisionReviewPackageExportSurfaceAccessDecisionReviewPackage({
  generated_at: 'not-a-date'
});
assert.equal(invalidGeneratedAt.state, HBCE_EXTERNAL_REVIEW_CANDIDATE_EVIDENCE_PACK_RUNTIME_READ_ACCESS_DECISION_REVIEW_PACKAGE_EXPORT_SURFACE_ACCESS_DECISION_REVIEW_PACKAGE_STATE.BLOCKED);
assert.equal(
  invalidGeneratedAt.reason,
  'HBCE_EXTERNAL_REVIEW_CANDIDATE_EVIDENCE_PACK_RUNTIME_READ_ACCESS_DECISION_REVIEW_PACKAGE_EXPORT_SURFACE_ACCESS_DECISION_REVIEW_PACKAGE_GENERATED_AT_INVALID'
);
const invalidCurrentTime = createExternalReviewCandidateEvidencePackRuntimeReadAccessDecisionReviewPackageExportSurfaceAccessDecisionReviewPackage({
  current_time: 'not-a-date'
});
assert.equal(invalidCurrentTime.state, HBCE_EXTERNAL_REVIEW_CANDIDATE_EVIDENCE_PACK_RUNTIME_READ_ACCESS_DECISION_REVIEW_PACKAGE_EXPORT_SURFACE_ACCESS_DECISION_REVIEW_PACKAGE_STATE.BLOCKED);
assert.equal(
  invalidCurrentTime.reason,
  'HBCE_EXTERNAL_REVIEW_CANDIDATE_EVIDENCE_PACK_RUNTIME_READ_ACCESS_DECISION_REVIEW_PACKAGE_EXPORT_SURFACE_ACCESS_DECISION_REVIEW_PACKAGE_CURRENT_TIME_INVALID'
);
console.log('PASS HBCE_EXTERNAL_REVIEW_CANDIDATE_EVIDENCE_PACK_RUNTIME_READ_ACCESS_DECISION_REVIEW_PACKAGE_EXPORT_SURFACE_ACCESS_DECISION_REVIEW_PACKAGE_INVALID_DATES');

const invalidSourceAuditIndex = createExternalReviewCandidateEvidencePackRuntimeReadAccessDecisionReviewPackageExportSurfaceAccessDecisionReviewPackage({
  source_audit_index_result: {
    state: 'BLOCKED',
    reason: 'SOURCE_AUDIT_INDEX_BLOCKED_FOR_TEST'
  }
});
assert.equal(invalidSourceAuditIndex.state, HBCE_EXTERNAL_REVIEW_CANDIDATE_EVIDENCE_PACK_RUNTIME_READ_ACCESS_DECISION_REVIEW_PACKAGE_EXPORT_SURFACE_ACCESS_DECISION_REVIEW_PACKAGE_STATE.BLOCKED);
assert.equal(
  invalidSourceAuditIndex.reason,
  'HBCE_EXTERNAL_REVIEW_CANDIDATE_EVIDENCE_PACK_RUNTIME_READ_ACCESS_DECISION_REVIEW_PACKAGE_EXPORT_SURFACE_ACCESS_DECISION_REVIEW_PACKAGE_SOURCE_AUDIT_INDEX_BLOCKED'
);
console.log('PASS HBCE_EXTERNAL_REVIEW_CANDIDATE_EVIDENCE_PACK_RUNTIME_READ_ACCESS_DECISION_REVIEW_PACKAGE_EXPORT_SURFACE_ACCESS_DECISION_REVIEW_PACKAGE_SOURCE_AUDIT_INDEX_BLOCKED');

const sourceAuditIndexResult = createExternalReviewCandidateEvidencePackRuntimeReadAccessDecisionReviewPackageExportSurfaceAccessDecisionAuditIndex();

const hashMismatchSource = clone(sourceAuditIndexResult);
hashMismatchSource.evidence_pack_runtime_read_access_decision_review_package_export_surface_access_decision_audit_index
  .evidence_pack_runtime_read_access_decision_review_package_export_surface_access_decision_audit_index_sha256 =
  '0'.repeat(64);
const invalidHash = createExternalReviewCandidateEvidencePackRuntimeReadAccessDecisionReviewPackageExportSurfaceAccessDecisionReviewPackage({
  source_audit_index_result: hashMismatchSource
});
assert.equal(invalidHash.state, HBCE_EXTERNAL_REVIEW_CANDIDATE_EVIDENCE_PACK_RUNTIME_READ_ACCESS_DECISION_REVIEW_PACKAGE_EXPORT_SURFACE_ACCESS_DECISION_REVIEW_PACKAGE_STATE.BLOCKED);
assert.equal(
  invalidHash.reason,
  'HBCE_EXTERNAL_REVIEW_CANDIDATE_EVIDENCE_PACK_RUNTIME_READ_ACCESS_DECISION_REVIEW_PACKAGE_EXPORT_SURFACE_ACCESS_DECISION_REVIEW_PACKAGE_SOURCE_AUDIT_INDEX_HASH_MISMATCH'
);
console.log('PASS HBCE_EXTERNAL_REVIEW_CANDIDATE_EVIDENCE_PACK_RUNTIME_READ_ACCESS_DECISION_REVIEW_PACKAGE_EXPORT_SURFACE_ACCESS_DECISION_REVIEW_PACKAGE_SOURCE_AUDIT_INDEX_HASH_MISMATCH');

const notObserveOnlySource = clone(sourceAuditIndexResult);
notObserveOnlySource.evidence_pack_runtime_read_access_decision_review_package_export_surface_access_decision_audit_index.observe_only_index_semantics =
  false;
const invalidObserveOnly = createExternalReviewCandidateEvidencePackRuntimeReadAccessDecisionReviewPackageExportSurfaceAccessDecisionReviewPackage({
  source_audit_index_result: notObserveOnlySource
});
assert.equal(invalidObserveOnly.state, HBCE_EXTERNAL_REVIEW_CANDIDATE_EVIDENCE_PACK_RUNTIME_READ_ACCESS_DECISION_REVIEW_PACKAGE_EXPORT_SURFACE_ACCESS_DECISION_REVIEW_PACKAGE_STATE.BLOCKED);
assert.equal(
  invalidObserveOnly.reason,
  'HBCE_EXTERNAL_REVIEW_CANDIDATE_EVIDENCE_PACK_RUNTIME_READ_ACCESS_DECISION_REVIEW_PACKAGE_EXPORT_SURFACE_ACCESS_DECISION_REVIEW_PACKAGE_SOURCE_AUDIT_INDEX_NOT_OBSERVE_ONLY'
);
console.log('PASS HBCE_EXTERNAL_REVIEW_CANDIDATE_EVIDENCE_PACK_RUNTIME_READ_ACCESS_DECISION_REVIEW_PACKAGE_EXPORT_SURFACE_ACCESS_DECISION_REVIEW_PACKAGE_SOURCE_AUDIT_INDEX_NOT_OBSERVE_ONLY');

const falseEffectsSource = clone(sourceAuditIndexResult);
falseEffectsSource.evidence_pack_runtime_read_access_decision_review_package_export_surface_access_decision_audit_index.external_review_execution_created =
  true;
const invalidFalseEffects = createExternalReviewCandidateEvidencePackRuntimeReadAccessDecisionReviewPackageExportSurfaceAccessDecisionReviewPackage({
  source_audit_index_result: falseEffectsSource
});
assert.equal(invalidFalseEffects.state, HBCE_EXTERNAL_REVIEW_CANDIDATE_EVIDENCE_PACK_RUNTIME_READ_ACCESS_DECISION_REVIEW_PACKAGE_EXPORT_SURFACE_ACCESS_DECISION_REVIEW_PACKAGE_STATE.BLOCKED);
assert.equal(
  invalidFalseEffects.reason,
  'HBCE_EXTERNAL_REVIEW_CANDIDATE_EVIDENCE_PACK_RUNTIME_READ_ACCESS_DECISION_REVIEW_PACKAGE_EXPORT_SURFACE_ACCESS_DECISION_REVIEW_PACKAGE_SOURCE_AUDIT_INDEX_FALSE_EFFECTS_INVALID'
);
console.log('PASS HBCE_EXTERNAL_REVIEW_CANDIDATE_EVIDENCE_PACK_RUNTIME_READ_ACCESS_DECISION_REVIEW_PACKAGE_EXPORT_SURFACE_ACCESS_DECISION_REVIEW_PACKAGE_SOURCE_AUDIT_INDEX_FALSE_EFFECTS_INVALID');
