'use strict';

const assert = require('assert');

const {
  createExternalReviewCandidateEvidencePackRuntimeReadAccessDecisionReviewPackageExportSurfaceAccessDecisionAuditEvent,
  HBCE_EXTERNAL_REVIEW_CANDIDATE_EVIDENCE_PACK_RUNTIME_READ_ACCESS_DECISION_REVIEW_PACKAGE_EXPORT_SURFACE_ACCESS_DECISION_AUDIT_EVENT_PROTO,
  HBCE_EXTERNAL_REVIEW_CANDIDATE_EVIDENCE_PACK_RUNTIME_READ_ACCESS_DECISION_REVIEW_PACKAGE_EXPORT_SURFACE_ACCESS_DECISION_AUDIT_EVENT_KIND,
  HBCE_EXTERNAL_REVIEW_CANDIDATE_EVIDENCE_PACK_RUNTIME_READ_ACCESS_DECISION_REVIEW_PACKAGE_EXPORT_SURFACE_ACCESS_DECISION_AUDIT_EVENT_STATE
} = require('../../runtime/external-review/create-external-review-candidate-evidence-pack-runtime-read-access-decision-review-package-export-surface-access-decision-audit-event');

function eventResult(input) {
  return createExternalReviewCandidateEvidencePackRuntimeReadAccessDecisionReviewPackageExportSurfaceAccessDecisionAuditEvent(input);
}

const actual = eventResult();
const body =
  actual.evidence_pack_runtime_read_access_decision_review_package_export_surface_access_decision_audit_event;
const payload = body.audit_event_payload;

assert.equal(actual.state, HBCE_EXTERNAL_REVIEW_CANDIDATE_EVIDENCE_PACK_RUNTIME_READ_ACCESS_DECISION_REVIEW_PACKAGE_EXPORT_SURFACE_ACCESS_DECISION_AUDIT_EVENT_STATE.READY);
assert.equal(actual.reason, 'HBCE_EXTERNAL_REVIEW_CANDIDATE_EVIDENCE_PACK_RUNTIME_READ_ACCESS_DECISION_REVIEW_PACKAGE_EXPORT_SURFACE_ACCESS_DECISION_AUDIT_EVENT_READY');
assert.equal(body.proto, HBCE_EXTERNAL_REVIEW_CANDIDATE_EVIDENCE_PACK_RUNTIME_READ_ACCESS_DECISION_REVIEW_PACKAGE_EXPORT_SURFACE_ACCESS_DECISION_AUDIT_EVENT_PROTO);
assert.equal(body.kind, HBCE_EXTERNAL_REVIEW_CANDIDATE_EVIDENCE_PACK_RUNTIME_READ_ACCESS_DECISION_REVIEW_PACKAGE_EXPORT_SURFACE_ACCESS_DECISION_AUDIT_EVENT_KIND);
assert.equal(
  body.audit_event_id,
  'HBCE-EXTERNAL-REVIEW-CANDIDATE-EVIDENCE-PACK-RUNTIME-READ-ACCESS-DECISION-REVIEW-PACKAGE-EXPORT-SURFACE-ACCESS-DECISION-AUDIT-EVENT-2026-09-23'
);
assert.match(body.evidence_pack_runtime_read_access_decision_review_package_export_surface_access_decision_audit_event_sha256, /^[a-f0-9]{64}$/);
console.log('PASS HBCE_EXTERNAL_REVIEW_CANDIDATE_EVIDENCE_PACK_RUNTIME_READ_ACCESS_DECISION_REVIEW_PACKAGE_EXPORT_SURFACE_ACCESS_DECISION_AUDIT_EVENT_READY');

assert.equal(body.audit_event_main_commit, 'f5ca975116eb7889f1d97904673930e163099ffc');
assert.equal(body.source_boundary_feature_commit, '4e750ab8da1c58fe51cd2d485ac7ca021dcf87b0');
assert.equal(body.source_boundary_merge_commit, '6e028b8f507ea08028c2d59ea671590fdb7ca6e3');
assert.equal(body.source_boundary_checkpoint_commit, '2a16282afdc5d543d9060475ad59e2a8e7245557');
assert.equal(body.source_boundary_final_chain_audit_commit, 'f5ca975116eb7889f1d97904673930e163099ffc');
assert.equal(body.source_boundary_checkpoint_doc_sha256, '39f46556db0fdd2ac066828ae410b449eaa019787ae9623ec7619cd933d960ed');
assert.equal(body.source_final_chain_audit_doc_sha256, '4e4c3e938eedfa4e38f176bae839035a1df552a08d83d5269ae304f6ffb618fc');
console.log('PASS HBCE_EXTERNAL_REVIEW_CANDIDATE_EVIDENCE_PACK_RUNTIME_READ_ACCESS_DECISION_REVIEW_PACKAGE_EXPORT_SURFACE_ACCESS_DECISION_AUDIT_EVENT_SOURCE_BOUNDARY');

assert.equal(body.source_boundary_sha256, 'bf75c55f1a4cc1ffcc3d0e634426ccb9b2f2ce72983070002da569791fdb0274');
assert.equal(body.source_boundary_payload_sha256, '6da4f545dbae6a25e7ed8f30b2ed08f65e1c73ef56bf6594affa6388d8f27a11');
assert.equal(payload.source_boundary_sha256, body.source_boundary_sha256);
assert.equal(payload.source_boundary_payload_sha256, body.source_boundary_payload_sha256);
assert.equal(payload.audit_event_payload_sha256, body.audit_event_payload_sha256);
console.log('PASS HBCE_EXTERNAL_REVIEW_CANDIDATE_EVIDENCE_PACK_RUNTIME_READ_ACCESS_DECISION_REVIEW_PACKAGE_EXPORT_SURFACE_ACCESS_DECISION_AUDIT_EVENT_HASHES');

assert.equal(body.audit_event_scope, 'INTERNAL_RUNTIME_READ_ACCESS_DECISION_REVIEW_PACKAGE_EXPORT_SURFACE_ACCESS_DECISION_AUDIT_EVENT_ONLY');
assert.equal(body.audit_event_consumer, 'JOKER_C2');
assert.equal(body.audit_event_category, 'AUDIT_OBSERVABILITY');
assert.equal(body.audit_event_subcategory, 'RUNTIME_READ_ACCESS_DECISION_REVIEW_PACKAGE_EXPORT_SURFACE_ACCESS_DECISION_AUDIT_EVENT');
assert.equal(body.append_only_audit_event_semantics, true);
assert.equal(body.observe_only_audit_event_semantics, true);
assert.equal(payload.audit_event_classification.decision_effect, 'OBSERVE_ONLY');
console.log('PASS HBCE_EXTERNAL_REVIEW_CANDIDATE_EVIDENCE_PACK_RUNTIME_READ_ACCESS_DECISION_REVIEW_PACKAGE_EXPORT_SURFACE_ACCESS_DECISION_AUDIT_EVENT_RECORD');

assert.equal(body.authority_resolution_state, 'VALID');
assert.equal(body.policy_decision, 'UNEVALUATED');
assert.equal(body.policy_decision_reason, 'POLICY_EVALUATION_DEFERRED');
assert.equal(body.authorization_state, 'UNRESOLVED');
assert.equal(body.authorization_reason, 'POLICY_NOT_RESOLVED');
assert.equal(body.positive_allow_probe_authorization_state, 'UNRESOLVED');
assert.equal(body.positive_allow_probe_authorization_reason, 'POSITIVE_AUTHORIZATION_DEFERRED');
assert.equal(payload.decision_snapshot.access_granted, false);
assert.equal(payload.decision_snapshot.creates_dispatch, false);
console.log('PASS HBCE_EXTERNAL_REVIEW_CANDIDATE_EVIDENCE_PACK_RUNTIME_READ_ACCESS_DECISION_REVIEW_PACKAGE_EXPORT_SURFACE_ACCESS_DECISION_AUDIT_EVENT_DECISION_SNAPSHOT');

assert.equal(payload.source_boundary_scope, 'INTERNAL_RUNTIME_READ_ACCESS_DECISION_REVIEW_PACKAGE_EXPORT_SURFACE_ACCESS_DECISION_BOUNDARY_ONLY');
assert.equal(payload.source_boundary_consumer, 'JOKER_C2');
assert.equal(payload.source_boundary_access_granted, false);
assert.equal(payload.source_boundary_grants_authorization, false);
assert.equal(payload.source_boundary_creates_authorization_artifact, false);
assert.equal(payload.source_boundary_executes_runtime_action, false);
assert.equal(payload.source_boundary_creates_dispatch, false);
assert.equal(payload.source_boundary_mutates_runtime_state, false);
console.log('PASS HBCE_EXTERNAL_REVIEW_CANDIDATE_EVIDENCE_PACK_RUNTIME_READ_ACCESS_DECISION_REVIEW_PACKAGE_EXPORT_SURFACE_ACCESS_DECISION_AUDIT_EVENT_SOURCE_BOUNDARY_VIEW');

assert.equal(body.source_binding_sha256, 'cb0e03f17c9f144e284d2b5fbfb265617893991c7c7ecefef2294825f2eb2f4f');
assert.equal(body.source_binding_payload_sha256, '09fd3d302e21a9117823d8f365b57b256b65a86c49cd77450a83e01adee6d5e2');
assert.equal(payload.source_index_sha256, '3f7c9aa821aac9f53e0ab0652a2cc235795059d55c9797ab32295508e7c7ed68');
assert.equal(payload.source_index_payload_sha256, 'b2a72f0cd85873c154a9bf511d0d7882c7972eb278459dc230492563187ea26a');
assert.equal(payload.source_surface_sha256, '57b0e3db62fe5354acf23b7f394feaf1bbc5197b51f9d9267d4cfe2a5c44fc1f');
assert.equal(payload.source_export_sha256, 'aa63a1a9b35aba093831fd7938c323cef5830d893c215cd766c01a6fd8f4c0c4');
assert.equal(payload.source_review_package_sha256, '86a19d81199457ecd6bc8f7d787862675f0403ddb6b34d73f17e8c35cc5b0bb5');
console.log('PASS HBCE_EXTERNAL_REVIEW_CANDIDATE_EVIDENCE_PACK_RUNTIME_READ_ACCESS_DECISION_REVIEW_PACKAGE_EXPORT_SURFACE_ACCESS_DECISION_AUDIT_EVENT_CHAIN_LINKAGE');

assert.equal(payload.stable_access_contract.deterministic_sha256_bound, true);
assert.equal(payload.stable_access_contract.source_boundary_hash_bound, true);
assert.equal(payload.stable_access_contract.append_only_audit_event_semantics, true);
assert.equal(payload.stable_access_contract.observe_only_audit_event_semantics, true);
assert.equal(payload.stable_access_contract.audit_event_does_not_authorize, true);
assert.equal(payload.stable_access_contract.audit_event_does_not_dispatch, true);
assert.equal(payload.stable_access_contract.audit_event_does_not_execute, true);
console.log('PASS HBCE_EXTERNAL_REVIEW_CANDIDATE_EVIDENCE_PACK_RUNTIME_READ_ACCESS_DECISION_REVIEW_PACKAGE_EXPORT_SURFACE_ACCESS_DECISION_AUDIT_EVENT_ACCESS_CONTRACT');

assert.equal(payload.assertions.audit_event_does_not_authorize, true);
assert.equal(payload.assertions.audit_event_does_not_dispatch, true);
assert.equal(payload.assertions.audit_event_does_not_execute, true);
assert.equal(payload.assertions.no_authorization_artifact_created, true);
assert.equal(body.grants_authorization, false);
assert.equal(body.creates_authorization_artifact, false);
assert.equal(body.creates_dispatch, false);
console.log('PASS HBCE_EXTERNAL_REVIEW_CANDIDATE_EVIDENCE_PACK_RUNTIME_READ_ACCESS_DECISION_REVIEW_PACKAGE_EXPORT_SURFACE_ACCESS_DECISION_AUDIT_EVENT_NON_AUTHORIZATION');

assert.equal(body.access_granted, false);
assert.equal(body.grants_authorization, false);
assert.equal(body.creates_authorization_artifact, false);
assert.equal(body.executes_runtime_action, false);
assert.equal(body.creates_dispatch, false);
assert.equal(body.mutates_runtime_state, false);
assert.equal(body.runtime_audit_log_mutated, false);
assert.equal(body.external_audit_log_mutated, false);
console.log('PASS HBCE_EXTERNAL_REVIEW_CANDIDATE_EVIDENCE_PACK_RUNTIME_READ_ACCESS_DECISION_REVIEW_PACKAGE_EXPORT_SURFACE_ACCESS_DECISION_AUDIT_EVENT_READ_ONLY');

assert.equal(body.public_registry_mutated, false);
assert.equal(body.external_trust_registry_mutated, false);
assert.equal(body.legal_certification_created, false);
assert.equal(body.eidas_qualification_created, false);
assert.equal(body.opc_allow_created, false);
assert.equal(body.deployment_success_proven, false);
assert.equal(body.production_deployment_proven, false);
console.log('PASS HBCE_EXTERNAL_REVIEW_CANDIDATE_EVIDENCE_PACK_RUNTIME_READ_ACCESS_DECISION_REVIEW_PACKAGE_EXPORT_SURFACE_ACCESS_DECISION_AUDIT_EVENT_FALSE_EFFECTS');

assert.equal(body.external_review_execution_created, false);
assert.equal(body.external_review_opinion_created, false);
assert.equal(body.external_review_report_created, false);
assert.equal(body.external_review_submission_created, false);
assert.equal(body.external_review_publication_created, false);
assert.equal(payload.assertions.no_external_review_execution_created, true);
assert.equal(payload.assertions.no_external_review_submission_created, true);
assert.equal(payload.assertions.no_external_review_publication_created, true);
console.log('PASS HBCE_EXTERNAL_REVIEW_CANDIDATE_EVIDENCE_PACK_RUNTIME_READ_ACCESS_DECISION_REVIEW_PACKAGE_EXPORT_SURFACE_ACCESS_DECISION_AUDIT_EVENT_NO_EXTERNAL_REVIEW');

assert.equal(payload.append_only_view.append_only, true);
assert.equal(payload.append_only_view.source_boundary_required, true);
assert.equal(payload.append_only_view.source_boundary_hash_bound, true);
assert.equal(payload.append_only_view.runtime_state_mutated_by_audit_event, false);
assert.equal(payload.append_only_view.external_registry_mutated_by_audit_event, false);
assert.equal(payload.assertions.append_only_audit_event_semantics, true);
console.log('PASS HBCE_EXTERNAL_REVIEW_CANDIDATE_EVIDENCE_PACK_RUNTIME_READ_ACCESS_DECISION_REVIEW_PACKAGE_EXPORT_SURFACE_ACCESS_DECISION_AUDIT_EVENT_APPEND_ONLY_SEMANTICS');

assert.equal(body.audit_event_does_not_authorize, true);
assert.equal(body.observe_only_audit_event_semantics, true);
assert.equal(payload.assertions.observe_only_audit_event_semantics, true);
assert.equal(payload.assertions.canonical_json_object, true);
assert.equal(payload.assertions.deterministic_sha256_bound, true);
assert.equal(payload.readable_summary.legal_certification_created, false);
assert.equal(payload.readable_summary.eidas_qualification_created, false);
assert.equal(payload.readable_summary.opc_allow_created, false);
console.log('PASS HBCE_EXTERNAL_REVIEW_CANDIDATE_EVIDENCE_PACK_RUNTIME_READ_ACCESS_DECISION_REVIEW_PACKAGE_EXPORT_SURFACE_ACCESS_DECISION_AUDIT_EVENT_OBSERVE_ONLY_SEMANTICS');

const first =
  eventResult().evidence_pack_runtime_read_access_decision_review_package_export_surface_access_decision_audit_event
    .evidence_pack_runtime_read_access_decision_review_package_export_surface_access_decision_audit_event_sha256;
const second =
  eventResult().evidence_pack_runtime_read_access_decision_review_package_export_surface_access_decision_audit_event
    .evidence_pack_runtime_read_access_decision_review_package_export_surface_access_decision_audit_event_sha256;
assert.equal(first, second);
console.log('PASS HBCE_EXTERNAL_REVIEW_CANDIDATE_EVIDENCE_PACK_RUNTIME_READ_ACCESS_DECISION_REVIEW_PACKAGE_EXPORT_SURFACE_ACCESS_DECISION_AUDIT_EVENT_DETERMINISTIC');

const invalidGeneratedAt = eventResult({ generated_at: 'not-a-date' });
assert.equal(invalidGeneratedAt.state, HBCE_EXTERNAL_REVIEW_CANDIDATE_EVIDENCE_PACK_RUNTIME_READ_ACCESS_DECISION_REVIEW_PACKAGE_EXPORT_SURFACE_ACCESS_DECISION_AUDIT_EVENT_STATE.BLOCKED);
assert.equal(
  invalidGeneratedAt.reason,
  'HBCE_EXTERNAL_REVIEW_CANDIDATE_EVIDENCE_PACK_RUNTIME_READ_ACCESS_DECISION_REVIEW_PACKAGE_EXPORT_SURFACE_ACCESS_DECISION_AUDIT_EVENT_GENERATED_AT_INVALID'
);
const invalidCurrentTime = eventResult({ current_time: 'not-a-date' });
assert.equal(invalidCurrentTime.state, HBCE_EXTERNAL_REVIEW_CANDIDATE_EVIDENCE_PACK_RUNTIME_READ_ACCESS_DECISION_REVIEW_PACKAGE_EXPORT_SURFACE_ACCESS_DECISION_AUDIT_EVENT_STATE.BLOCKED);
assert.equal(
  invalidCurrentTime.reason,
  'HBCE_EXTERNAL_REVIEW_CANDIDATE_EVIDENCE_PACK_RUNTIME_READ_ACCESS_DECISION_REVIEW_PACKAGE_EXPORT_SURFACE_ACCESS_DECISION_AUDIT_EVENT_CURRENT_TIME_INVALID'
);
console.log('PASS HBCE_EXTERNAL_REVIEW_CANDIDATE_EVIDENCE_PACK_RUNTIME_READ_ACCESS_DECISION_REVIEW_PACKAGE_EXPORT_SURFACE_ACCESS_DECISION_AUDIT_EVENT_INVALID_DATES');

const invalidSourceBoundary = eventResult({
  source_boundary_result: {
    state: 'BLOCKED',
    reason: 'SOURCE_BOUNDARY_BLOCKED_FOR_TEST'
  }
});
assert.equal(invalidSourceBoundary.state, HBCE_EXTERNAL_REVIEW_CANDIDATE_EVIDENCE_PACK_RUNTIME_READ_ACCESS_DECISION_REVIEW_PACKAGE_EXPORT_SURFACE_ACCESS_DECISION_AUDIT_EVENT_STATE.BLOCKED);
assert.equal(
  invalidSourceBoundary.reason,
  'HBCE_EXTERNAL_REVIEW_CANDIDATE_EVIDENCE_PACK_RUNTIME_READ_ACCESS_DECISION_REVIEW_PACKAGE_EXPORT_SURFACE_ACCESS_DECISION_AUDIT_EVENT_SOURCE_BOUNDARY_BLOCKED'
);
console.log('PASS HBCE_EXTERNAL_REVIEW_CANDIDATE_EVIDENCE_PACK_RUNTIME_READ_ACCESS_DECISION_REVIEW_PACKAGE_EXPORT_SURFACE_ACCESS_DECISION_AUDIT_EVENT_SOURCE_BOUNDARY_BLOCKED');

const invalidHashBody = {
  ...body,
  evidence_pack_runtime_read_access_decision_review_package_export_surface_access_decision_boundary_sha256: '0'.repeat(64),
  access_decision_payload_sha256: '6da4f545dbae6a25e7ed8f30b2ed08f65e1c73ef56bf6594affa6388d8f27a11'
};
const invalidHash = eventResult({
  source_boundary_result: {
    state: 'READY',
    evidence_pack_runtime_read_access_decision_review_package_export_surface_access_decision_boundary: invalidHashBody
  }
});
assert.equal(invalidHash.state, HBCE_EXTERNAL_REVIEW_CANDIDATE_EVIDENCE_PACK_RUNTIME_READ_ACCESS_DECISION_REVIEW_PACKAGE_EXPORT_SURFACE_ACCESS_DECISION_AUDIT_EVENT_STATE.BLOCKED);
assert.equal(
  invalidHash.reason,
  'HBCE_EXTERNAL_REVIEW_CANDIDATE_EVIDENCE_PACK_RUNTIME_READ_ACCESS_DECISION_REVIEW_PACKAGE_EXPORT_SURFACE_ACCESS_DECISION_AUDIT_EVENT_SOURCE_BOUNDARY_HASH_MISMATCH'
);
console.log('PASS HBCE_EXTERNAL_REVIEW_CANDIDATE_EVIDENCE_PACK_RUNTIME_READ_ACCESS_DECISION_REVIEW_PACKAGE_EXPORT_SURFACE_ACCESS_DECISION_AUDIT_EVENT_SOURCE_BOUNDARY_HASH_MISMATCH');

const invalidFailClosedBody = {
  ...body,
  evidence_pack_runtime_read_access_decision_review_package_export_surface_access_decision_boundary_sha256: 'bf75c55f1a4cc1ffcc3d0e634426ccb9b2f2ce72983070002da569791fdb0274',
  access_decision_payload_sha256: '6da4f545dbae6a25e7ed8f30b2ed08f65e1c73ef56bf6594affa6388d8f27a11',
  access_granted: true
};
const invalidFailClosed = eventResult({
  source_boundary_result: {
    state: 'READY',
    evidence_pack_runtime_read_access_decision_review_package_export_surface_access_decision_boundary: invalidFailClosedBody
  }
});
assert.equal(invalidFailClosed.state, HBCE_EXTERNAL_REVIEW_CANDIDATE_EVIDENCE_PACK_RUNTIME_READ_ACCESS_DECISION_REVIEW_PACKAGE_EXPORT_SURFACE_ACCESS_DECISION_AUDIT_EVENT_STATE.BLOCKED);
assert.equal(
  invalidFailClosed.reason,
  'HBCE_EXTERNAL_REVIEW_CANDIDATE_EVIDENCE_PACK_RUNTIME_READ_ACCESS_DECISION_REVIEW_PACKAGE_EXPORT_SURFACE_ACCESS_DECISION_AUDIT_EVENT_SOURCE_BOUNDARY_NOT_FAIL_CLOSED'
);
console.log('PASS HBCE_EXTERNAL_REVIEW_CANDIDATE_EVIDENCE_PACK_RUNTIME_READ_ACCESS_DECISION_REVIEW_PACKAGE_EXPORT_SURFACE_ACCESS_DECISION_AUDIT_EVENT_SOURCE_BOUNDARY_NOT_FAIL_CLOSED');

const invalidFalseEffectsBody = {
  ...body,
  evidence_pack_runtime_read_access_decision_review_package_export_surface_access_decision_boundary_sha256: 'bf75c55f1a4cc1ffcc3d0e634426ccb9b2f2ce72983070002da569791fdb0274',
  access_decision_payload_sha256: '6da4f545dbae6a25e7ed8f30b2ed08f65e1c73ef56bf6594affa6388d8f27a11',
  external_review_execution_created: true
};
const invalidFalseEffects = eventResult({
  source_boundary_result: {
    state: 'READY',
    evidence_pack_runtime_read_access_decision_review_package_export_surface_access_decision_boundary: invalidFalseEffectsBody
  }
});
assert.equal(invalidFalseEffects.state, HBCE_EXTERNAL_REVIEW_CANDIDATE_EVIDENCE_PACK_RUNTIME_READ_ACCESS_DECISION_REVIEW_PACKAGE_EXPORT_SURFACE_ACCESS_DECISION_AUDIT_EVENT_STATE.BLOCKED);
assert.equal(
  invalidFalseEffects.reason,
  'HBCE_EXTERNAL_REVIEW_CANDIDATE_EVIDENCE_PACK_RUNTIME_READ_ACCESS_DECISION_REVIEW_PACKAGE_EXPORT_SURFACE_ACCESS_DECISION_AUDIT_EVENT_SOURCE_BOUNDARY_FALSE_EFFECTS_INVALID'
);
console.log('PASS HBCE_EXTERNAL_REVIEW_CANDIDATE_EVIDENCE_PACK_RUNTIME_READ_ACCESS_DECISION_REVIEW_PACKAGE_EXPORT_SURFACE_ACCESS_DECISION_AUDIT_EVENT_SOURCE_BOUNDARY_FALSE_EFFECTS_INVALID');
